apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://metrics:9090
    isDefault: true
  - name: Loki
    type: loki
    access: proxy
    url: http://logging:3100
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tracing:3200
